### PR TITLE
Feature/add dashboard component

### PR DESCRIPTION
**Pull request by fabiangotzen**

### CODE REVIEW

**Comment by fabiangotzen** [comment]
preview: 
image

**Comment by laggery** [comment]
What was the problem with the other logo? Personally I liked it.
This logo is perhaps more a wing. what do you think

**Comment by laggery** [comment]
Bugs:
- After login amount of flights is 0
- Amount of flights show every time 20. This is the default limit.
   You can use the following request:
   {{baseUrl}}/flights/statistic or {{baseUrl}}/places/pager

Design:
- For me the copy of the flights on the Dashboard is not clear enough. I thought I had opened the last flights. Maybe we can 
   open the last flight. This would make it possible to do changes on the last flight but also to copy it.
   What do you think?

**Comment by laggery** [comment]
image
Design from “amount of flights” in English

**Comment by fabiangotzen** [comment]
> Bugs:
> 
> * After login amount of flights is 0
> * Amount of flights show every time 20. This is the default limit.
>   You can use the following request:
>   {{baseUrl}}/flights/statistic or {{baseUrl}}/places/pager
> 
> Design:
> 
> * For me the copy of the flights on the Dashboard is not clear enough. I thought I had opened the last flights. Maybe we can
>   open the last flight. This would make it possible to do changes on the last flight but also to copy it.
>   What do you think?

* Should work now -> When you have flights they should be displayed, if not it shows 0 flights
* Fixed, used the statistics endpoint which now goes over the default limit of 20

* Design: I've abbreviated it for the moment to no. of flights. For modern smartphones the design should work now. I've changed it to open the "edit flight" modal now. I've also decided to cut out the dynamic start name of the last flight for now, since it also causes issues to the design depending on the length. (I'll have a look at it in a seperate PR so we can merge this one) 

image
image

**Comment by laggery** [comment]
> > Bugs:
> > 
> > * After login amount of flights is 0
> > * Amount of flights show every time 20. This is the default limit.
> >   You can use the following request:
> >   {{baseUrl}}/flights/statistic or {{baseUrl}}/places/pager
> > 
> > Design:
> > 
> > * For me the copy of the flights on the Dashboard is not clear enough. I thought I had opened the last flights. Maybe we can
> >   open the last flight. This would make it possible to do changes on the last flight but also to copy it.
> >   What do you think?
> 
> * Should work now -> When you have flights they should be displayed, if not it shows 0 flights
> * Fixed, used the statistics endpoint which now goes over the default limit of 20
> * Design: I've abbreviated it for the moment to no. of flights. For modern smartphones the design should work now. I've changed it to open the "edit flight" modal now. I've also decided to cut out the dynamic start name of the last flight for now, since it also causes issues to the design depending on the length. (I'll have a look at it in a seperate PR so we can merge this one)
> 
> image
> image

Design bug:
image

On IPad and higher resolution "no. of flights" is not correctly displayed.
Capitalize the first letter of the dashboard items?

**Review by laggery — APPROVED** [review]

**Pull request merged**
